//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNCTool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CNCTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (originally Generated by PartKam Version 0.05)
        ///
        ///G20 G90 (remove G40)
        ///
        ///(write the words)
        ///G0 Z0.125
        ///(remove x)
        ///G17
        ///
        ///G0 X0.435 Y0.4042
        ///G1 Z-0.01 F10
        ///G3 X0.4557 Y0.4046 I0 J0.4533 F40
        ///G3 X0.4728 Y0.4059 I-0.0142 J0.3117
        ///G3 X0.4898 Y0.4082 I-0.0257 J0.2542
        ///G3 X0.5034 Y0.4111 I-0.028 J0.1653
        ///G3 X0.5168 Y0.415 I-0.0472 J0.1844
        ///G3 X0.5278 Y0.4192 I-0.0435 J0.1296
        ///G3 X0.5383 Y0.4245 I-0.0462 J0.1062
        ///G3 X0.5468 Y0.4299 I-0.0415 J0.0739
        ///G3 X0.5545 Y0.4363 I-0.0474 J0.0649
        ///G3 X0.5606 Y0.4429 I-0.0441 J0.0468
        ///G3 X0.5656 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ShapeokoLogo {
            get {
                return ResourceManager.GetString("ShapeokoLogo", resourceCulture);
            }
        }
    }
}
